# Site settings
repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2
darkmode: true

# Contact information
name: "Andrei Gritsenko"
title: "ML Engineer & Python Backend Developer"
email: "andgr1it@gmail.com"
phone: "+995 (591) 011380"
website: "https://angr1it.github.io"
location: "Tbilisi, Georgia"
description: "LLM systems & scalable backend expert with 6+ years in AI/ML and Python infrastructure"

# Social links
linkedin_username: "andrei-gritsenko-5a315332b"
github_username: "angr1it"

additional_links:
# - title: GitHub
#   icon: fab fa-github
#   url: https://github.com/angr1it
- title: Telegram
  icon: fab fa-telegram
  url: https://t.me/andregrit

# About section
about_title: "About Me"
about_profile_image: images/profile.jpg
about_content: |
  ML engineer with a strong backend background, specializing in production-grade AI agents and LLM systems. 
  Experienced with model fine-tuning (LoRA, PEFT), RAG architecture, and LangChain-based applications. 
  Skilled in deploying scalable microservices with FastAPI, Celery, PostgreSQL, Docker, and Kubernetes. 
  Proficient in both classical ML (scikit-learn, CatBoost, XGBoost) and modern LLM pipelines (OpenAI, RAG, Tool Use).
  Focused on robust architecture, observability, and clean code in real-world environments.

# Main content
content:
- title: "Work Experience"
  layout: list
  content:
  - layout: top
    title: "Rainex.io"
    sub_title: "Python Backend / ML Engineer"
    caption: "Feb 2024 – Present"
    description: |
      - Designed and implemented a lead generation platform for the B2C segment: built a recommendation system using embeddings, LLMs (GPT-4), and Retrieval-Augmented Generation (RAG) techniques. Improved recommendation accuracy by 30% (based on internal metrics).
      - Developed RAG pipelines (Weaviate, LangChain, OpenAI API) — boosted relevance by 25%, reduced latency to 450 ms.
      - Created LLM agents for chat and recommendation tasks (LangChain Agents, Tool calling, gpt-4o-mini) — +18% NDCG.
      - Implemented preprocessing and vectorization pipelines — 4× faster unstructured data analysis.
      - Designed high-load backend services (FastAPI, Celery, PostgreSQL, MongoDB); built crawler for 50K+ sources.
      - Scaled Celery to 300+ req/s with retries and monitoring (Flower, Sentry).
      - Deployed services via GitLab CI to Kubernetes with 99.9% SLA.
      - Fine-tuned BERT models — reduced OpenAI API calls and inference cost by 35%.
      - Built internal tools for MCP agent workflows and an embedding-based discovery layer for A2A orchestration.
      - Led a backend team (3 engineers): architecture, planning, code reviews.

  - layout: top
    title: "Consyst-OC"
    sub_title: "Backend Engineer"
    caption: "Apr 2019 – Feb 2024"
    link: "https://www.consyst-oc.ru/"
    description: |
      - Developed ETL pipelines processing tens of thousands of records daily.
      - Designed and integrated REST APIs and microservices for scalable systems.
      - Built database architectures and optimized SQL queries — up to 10x speedup.
      - Created Python and Groovy libraries extending Apache NiFi capabilities.
      - Automated business processes and complex data workflows using Python, Groovy, Apache NiFi, and SQL.

- title: "Education"
  layout: list
  content:
  - layout: left
    title: "Moscow Institute of Physics and Technology (MIPT)"
    sub_title: "Master's, Data Science"
    caption: "2025"
  - layout: left
    title: "Moscow State University (MSU)"
    sub_title: "Bachelor’s in Applied Mathematics and Physics"
    caption: "2019"

- title: "Certifications"
  layout: list
  content:
  - layout: top
    title: "Asynchronous programming in Python (async, asyncio)"
    caption: "2023, practicum.yandex"
  - layout: top
    title: "Deep Learning — School of Deep Learning, FPMI MIPT"
    caption: "2023, Stepik"
  - layout: top
    title: "Advanced machine learning models"
    caption: "2024, MTPT"

- title: "Skills"
  layout: text
  content: |
    **Languages & Tools:** Python, SQL, Git, Bash, Makefile, Poetry  
    **Backend & APIs:** FastAPI, SQLAlchemy, REST API, gRPC, OOP, TDD, Unit Testing  
    **Databases:** PostgreSQL, MongoDB, Redis, Weaviate, ChromaDB  
    **ML & AI:** PyTorch, scikit-learn, pandas, numpy, CatBoost, XGBoost, LightGBM, LoRA, PEFT, llama.cpp, unsloth  
    **LLM & NLP:** OpenAI, GPT-4, GPT-4o-mini, LangChain, RAG, Tool Use, Agents, Prompt Engineering  
    **Infrastructure:** Docker, Kubernetes, GitLab CI/CD, Flower, Sentry, Kafka, Airflow, Celery  
    **Other:** Apache NiFi, Data Science, Data Engineering, MLflow

- title: "Languages"
  layout: text
  content: |
    - Russian — Native  
    - English — B2 (Upper-Intermediate)

- title: "Other Information"
  layout: text
  content: |
    - Citizenship: Russia  
    - Location: Tbilisi, Georgia  
    - Relocation: Ready

# Footer and build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

include:
- assets/fonts

plugins:
- jekyll-seo-tag

relative_links:
  enabled: true
